--liquibase formatted sql

--changeset sukhov:8

CREATE TABLE T_SUPERTASK_SOLUTION
(
	SUPERTASK_SOLUTION_ID		SERIAL PRIMARY KEY,
	SUPERTASK_ID				INTEGER NOT NULL,
	USER_ID						INTEGER NOT NULL,
	TASK_NUM					SMALLINT NOT NULL,
	SUPERTASK_VERSION_NUMBER	INTEGER,
	CONTEST_ID					INTEGER,
	SOLUTION_STATUS				SMALLINT,
	SOLUTION_KEY				SMALLINT,
	SOLUTION_DESC				VARCHAR(512),
	SAVE_DTM					TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SOLUTION_WORKSPACE_XML		TEXT
);

COMMENT ON TABLE T_SUPERTASK_SOLUTION IS 'Сохранённые решения задачи - сохраняются в виде Blockly DOM Workspace';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SUPERTASK_SOLUTION_ID IS 'ID решения';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SUPERTASK_ID IS 'ID суперзадачи, к которой относится решение';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.USER_ID IS 'ID пользователя автора решения';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.TASK_NUM IS 'Номер задачи в подзадаче (нумерация с 0)';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SUPERTASK_VERSION_NUMBER IS 'Номер версии суперзадачи. Может быть пустым, если решение - решение разработчика вне соревнования';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.CONTEST_ID IS 'ID соревнования. Может быть пустым, если решение - решение разработчика вне соревнования';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SOLUTION_STATUS IS 'Статус решения в соответствии с T_SUPERTASK_SOLUTION_STATUS';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SOLUTION_KEY IS 'Дополнительный числовой ключ решения -  чтобы можно было сохранять несколько решений и отмечать их номерами';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SOLUTION_DESC IS 'Описание решения';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SAVE_DTM IS 'Дата и время сохранения';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION.SOLUTION_WORKSPACE_XML IS 'Решение в формате Blockly DOM Workspace XML';

--rollback drop table T_SUPERTASK_SOLUTION;

--

CREATE TABLE T_SUPERTASK_SOLUTION_STATUS
(
	SUPERTASK_SOLUTION_STATUS_ID	SMALLINT PRIMARY KEY,
	SUPERTASK_SOLUTION_STATUS_NAME	VARCHAR(256),
	SUPERTASK_SOLUTION_STATUS_DESC	VARCHAR(512)
);

COMMENT ON TABLE T_SUPERTASK_SOLUTION_STATUS IS 'Статусы решений задачи';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION_STATUS.SUPERTASK_SOLUTION_STATUS_ID IS 'ID статуса';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION_STATUS.SUPERTASK_SOLUTION_STATUS_NAME IS 'Название статуса решения';
COMMENT ON COLUMN T_SUPERTASK_SOLUTION_STATUS.SUPERTASK_SOLUTION_STATUS_DESC IS 'Описание статуса решения';

INSERT INTO T_SUPERTASK_SOLUTION_STATUS(SUPERTASK_SOLUTION_STATUS_ID, SUPERTASK_SOLUTION_STATUS_NAME, SUPERTASK_SOLUTION_STATUS_DESC)
VALUES(1, 'Решение разработчика', 'Решение разработчика задачи - не привязано к контесту');

INSERT INTO T_SUPERTASK_SOLUTION_STATUS(SUPERTASK_SOLUTION_STATUS_ID, SUPERTASK_SOLUTION_STATUS_NAME, SUPERTASK_SOLUTION_STATUS_DESC)
VALUES(2, 'Текущее решение', 'Текущее решение - сохраняетя автоматически');

INSERT INTO T_SUPERTASK_SOLUTION_STATUS(SUPERTASK_SOLUTION_STATUS_ID, SUPERTASK_SOLUTION_STATUS_NAME, SUPERTASK_SOLUTION_STATUS_DESC)
VALUES(3, 'Лучшее решение', 'Решение с максимальным баллом');

INSERT INTO T_SUPERTASK_SOLUTION_STATUS(SUPERTASK_SOLUTION_STATUS_ID, SUPERTASK_SOLUTION_STATUS_NAME, SUPERTASK_SOLUTION_STATUS_DESC)
VALUES(4, 'Сохранённое решение', 'Решение, сохранённое участником');

--rollback drop table T_SUPERTASK_SOLUTION_STATUS;