--liquibase formatted sql

--changeset sukhov:10

CREATE UNIQUE INDEX T_SUPERTASK_SOLUTION_INDEX 
ON T_SUPERTASK_SOLUTION (SUPERTASK_ID, USER_ID, TASK_NUM, CONTEST_ID, SOLUTION_STATUS, SOLUTION_KEY)
NULLS NOT DISTINCT;


--changeset sukhov:11

CREATE UNIQUE INDEX T_SUPERTASK_RESULT_INDEX 
ON T_SUPERTASK_RESULT (SUPERTASK_ID, USER_ID, TASK_NUM, CONTEST_ID)
NULLS NOT DISTINCT;

