--liquibase formatted sql

--changeset sukhov:19

ALTER TABLE T_CONTEST ADD COLUMN CONTEST_START_TIME TIMESTAMP WITH TIME ZONE;
ALTER TABLE T_CONTEST ADD COLUMN GMT_OFFSET INTEGER NOT NULL DEFAULT 0;
ALTER TABLE T_CONTEST ADD COLUMN CONTEST_DURATION INTEGER NOT NULL DEFAULT 120;
ALTER TABLE T_CONTEST ADD COLUMN NO_END_TIME BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE T_CONTEST ADD COLUMN VIRTUAL_PARTICIPATION BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE T_CONTEST ADD COLUMN LIMIT_VIRTUAL_START BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE T_CONTEST ADD COLUMN VIRTUAL_START_END_TIME TIMESTAMP WITH TIME ZONE;

COMMENT ON COLUMN T_CONTEST.CONTEST_START_TIME IS 'Дата и время начала соревнования';
COMMENT ON COLUMN T_CONTEST.GMT_OFFSET IS 'Смещение часового пояса относительно GMT (в часах). Применяется к CONTEST_START_TIME и VIRTUAL_START_END_TIME при отображении в мастере редактирования соревнования';
COMMENT ON COLUMN T_CONTEST.CONTEST_DURATION IS 'Длительность соревнования в минутах';
COMMENT ON COLUMN T_CONTEST.NO_END_TIME IS 'Признак бесконечного соревнования (нет времени окончания)';
COMMENT ON COLUMN T_CONTEST.VIRTUAL_PARTICIPATION IS 'Разрешено виртуальное участие (плавающий старт)';
COMMENT ON COLUMN T_CONTEST.LIMIT_VIRTUAL_START IS 'Ограничено ли окно старта виртуального участия';
COMMENT ON COLUMN T_CONTEST.VIRTUAL_START_END_TIME IS 'Дата и время окончания окна старта виртуального участия';

--rollback ALTER TABLE T_CONTEST DROP COLUMN VIRTUAL_START_END_TIME; ALTER TABLE T_CONTEST DROP COLUMN LIMIT_VIRTUAL_START; ALTER TABLE T_CONTEST DROP COLUMN VIRTUAL_PARTICIPATION; ALTER TABLE T_CONTEST DROP COLUMN NO_END_TIME; ALTER TABLE T_CONTEST DROP COLUMN CONTEST_DURATION; ALTER TABLE T_CONTEST DROP COLUMN GMT_OFFSET; ALTER TABLE T_CONTEST DROP COLUMN CONTEST_START_TIME;


